// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'us-east-1',
  'aws_cognito_identity_pool_id': 'us-east-1:5378bbe5-6e1a-48e9-981b-881c03b18791',
  'aws_cognito_region': 'us-east-1',
  'aws_user_pools_id': 'us-east-1_ppcMutfsX',
  'aws_user_pools_web_client_id': '3lrvprdhjv711n3grvdt7i2iu7',
  'aws_content_delivery_bucket': 'donalolaapp-20181020192438--hostingbucket',
  'aws_content_delivery_bucket_region': 'us-east-1',
  'aws_content_delivery_url': 'http://donalolaapp-20181020192438--hostingbucket.s3-website-us-east-1.amazonaws.com'
}

export default awsmobile
